application: tinywebdb
version: 1.2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

handlers:
- url: /images
  static_dir: images

- url: .*
  script: main.app



