application: tinywebdb-nointerface
version: 3
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

handlers:
- url: /images
  static_dir: images
  secure: always

- url: .*
  script: main.app